### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by sedlund** [srevinsaju/element-appimage#3]
Element--GLIBC-2.31_91760c3510b4feec17937ee095998677.AppImage

![element-failed-to-start-2021-07-09_09-30](https://user-images.githubusercontent.com/8109138/125093957-77883c80-e098-11eb-8f24-a0b128afda98.png)

**Comment by srevinsaju** [comment]
Oh, thanks or reporting! I will fix it in a while. :smile:

**Comment by spsf64** [comment]
It worked just once (after first try), after that I always get just a blank screen...
Element--GLIBC-2.31_91760c3510b4feec17937ee095998677.AppImage

![Screenshot from 2021-07-09 10-36-27](https://user-images.githubusercontent.com/1877391/125094897-a48d1d00-e0a1-11eb-9bfd-5e73050a594e.png)

**Comment by srevinsaju** [comment]
Can you run it from the terminal? Maybe we should get some clues of the error from there

PS: I have lost track of the versions. Can you cross check if its the latest AppImage from the stable releases? The current stable releases do not have a commit hash in their filename :thinking:

**Comment by spsf64** [comment]
> Can you run it from the terminal? Maybe we should get some clues of the error from there
> 
> PS: I have lost track of the versions. Can you cross check if its the latest AppImage from the stable releases? The current stable releases do not have a commit hash in their filename

Ohhh, it works... Sorry for not trying this... 
I am running archlinux+cinnamon and using AppImager to "install" it and create the .desktop shortcut in the menu, probably the culprit...

**Comment by sedlund** [comment]
It is the latest.  I click ran it, and Appimage 'installs' it to the ~/Applications directory where it adds the hash (I assume for upgrading).

Here is the console output.

```
╰─ ./Element--GLIBC-2.31_91760c3510b4feec17937ee095998677.AppImage 
Element AppImage Build
Seshat unexpected error: Error: libsqlcipher.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_Elemen7hF02A/resources/app.asar/node_modules/matrix-seshat/lib/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
/home/sedlund/.config/Element exists: no
/home/sedlund/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
Changing application language to en-us,en
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js
- /tmp/.mount_Elemen7hF02A/resources/app.asar/src/tray.js
- /tmp/.mount_Elemen7hF02A/resources/app.asar/src/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js:83:20)
    at /tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js:102:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js:101:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js',
    '/tmp/.mount_Elemen7hF02A/resources/app.asar/src/tray.js',
    '/tmp/.mount_Elemen7hF02A/resources/app.asar/src/electron-main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Could not fetch translation json for locale: 'en' Error: Cannot find module './i18n/strings/en.json'
Require stack:
- /tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js
- /tmp/.mount_Elemen7hF02A/resources/app.asar/src/tray.js
- /tmp/.mount_Elemen7hF02A/resources/app.asar/src/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js:83:20)
    at /tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js:102:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js:101:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_Elemen7hF02A/resources/app.asar/src/language-helper.js',
    '/tmp/.mount_Elemen7hF02A/resources/app.asar/src/tray.js',
    '/tmp/.mount_Elemen7hF02A/resources/app.asar/src/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
```

**Comment by srevinsaju** [comment]
> I am running archlinux+cinnamon and using AppImager to "install" it and create the .desktop shortcut in the menu, probably the culprit...

@spsf64 Try [`zap`](https://github.com/srevinsaju/zap) next time :smile: . Homegrown appimage package manager ✨

> Could not fetch translation json for locale: 'en' Error: Cannot find module './i18n/strings/en.json'

@sedlund interesting. Let me test these builds. Never happened to see this before. It looks like the files needed for translation is missing :thinking:

**Comment by spsf64** [comment]
> > I am running archlinux+cinnamon and using AppImager to "install" it and create the .desktop shortcut in the menu, probably the culprit...
> 
> @spsf64 Try [`zap`](https://github.com/srevinsaju/zap) next time  . Homegrown appimage package manager 
> 
I will definitely check this out...
Thanks!!

**Comment by gerhardbeck** [comment]
Same error:
![grafik](https://user-images.githubusercontent.com/41069802/149137056-eade0856-d79f-4760-ab56-6e4f1afc83f4.png)

But solution seems to be in #5 , but has to be integrated in the appimage

**Comment by srevinsaju** [comment]
Fixed in https://github.com/srevinsaju/element-appimage/commit/83b0d2f2659b3e649ff66d75372cd8dc3e4f0274, let me know if the issue still persists.
